CREATE TABLE CONTRACT_TYPE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME NVARCHAR(100),
    DESCRIPTION NVARCHAR(1000),
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME
);

CREATE TABLE CONTRACT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    DESCRIPTION NVARCHAR(1000),
    START_DATE DATE,
    END_DATE DATE,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    TYPE_ID INT,
    FOREIGN KEY (TYPE_ID) REFERENCES CONTRACT_TYPE(ID)
);

CREATE TABLE DEPARTMENT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    NAME NVARCHAR(100)
);

CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRST_NAME NVARCHAR(100),
    LAST_NAME NVARCHAR(100),
    PHONE_NUMBER VARCHAR(100),
    SALARY DECIMAL,
    CREATE_BY INT,
    CREATE_TIME DATETIME,
    UPDATE_BY INT,
    UPDATE_TIME DATETIME,
    CONTRACT_ID INT,
    DEPARTMENT_ID INT,
    FOREIGN KEY (CONTRACT_ID) REFERENCES CONTRACT(ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

CREATE TABLE ACCOUNT(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME NVARCHAR(100),
    PASSWORD NVARCHAR(100),
    ROLE NVARCHAR(100),
    CREATE_TIME DATETIME,
    UPDATE_TIME DATETIME,
    EMPLOYEE_ID INT,
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);

CREATE TRIGGER CONTRACT_TYPE_CREATE_TIMESTAMP BEFORE INSERT ON CONTRACT_TYPE
FOR EACH ROW
SET NEW.CREATE_TIME = NOW();

CREATE TRIGGER CONTRACT_CREATE_TIMESTAMP BEFORE INSERT ON CONTRACT
FOR EACH ROW
SET NEW.CREATE_TIME = NOW();

CREATE TRIGGER DEPARTMENT_CREATE_TIMESTAMP BEFORE INSERT ON DEPARTMENT
FOR EACH ROW
SET NEW.CREATE_TIME = NOW();

CREATE TRIGGER EMPLOYEE_CREATE_TIMESTAMP BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
SET NEW.CREATE_TIME = NOW();

CREATE TRIGGER ACCOUNT_CREATE_TIMESTAMP BEFORE INSERT ON ACCOUNT
FOR EACH ROW
SET NEW.CREATE_TIME = NOW();

CREATE TRIGGER CONTRACT_TYPE_UPDATE_TIMESTAMP BEFORE UPDATE ON CONTRACT_TYPE
FOR EACH ROW
SET NEW.UPDATE_TIME = NOW();

CREATE TRIGGER CONTRACT_UPDATE_TIMESTAMP BEFORE UPDATE ON CONTRACT
FOR EACH ROW
SET NEW.UPDATE_TIME = NOW();

CREATE TRIGGER DEPARTMENT_UPDATE_TIMESTAMP BEFORE UPDATE ON DEPARTMENT
FOR EACH ROW
SET NEW.UPDATE_TIME = NOW();

CREATE TRIGGER EMPLOYEE_UPDATE_TIMESTAMP BEFORE UPDATE ON EMPLOYEE
FOR EACH ROW
SET NEW.UPDATE_TIME = NOW();

CREATE TRIGGER ACCOUNT_UPDATE_TIMESTAMP BEFORE UPDATE ON ACCOUNT
FOR EACH ROW
SET NEW.UPDATE_TIME = NOW();

INSERT INTO ACCOUNT(USERNAME, PASSWORD, ROLE) VALUES ('admin', 'admin', 'ADMIN');
